// หากคุณใช้ TypeScript ให้ใช้ .tsx / ถ้าใช้ JavaScript ให้เปลี่ยนนามสกุลเป็น .jsx
import "./globals.css";
import { Mali } from "next/font/google"; // ⬅️ เพิ่มตรงนี้

const mali = Mali({
  subsets: ["thai", "latin"], // ⬅️ ใช้ subsets ที่มีภาษาไทย
  weight: ["400", "700"], // ⬅️ เลือกน้ำหนักที่ต้องการ
  variable: "--font-mali", // ⬅️ ตั้งชื่อไว้ใช้ใน class
});

export const metadata = {
  title: "My Job",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${mali.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
